// Wire protocol constants and validation helpers.
//
// Message types travel as JSON over a single WebSocket. Coordinate system:
//   - originXFrac / originYFrac: floats in [0,1], fractions of sender viewport.
//     Receivers multiply by their own viewport to place the stroke.
//   - points: engine-native coordinates relative to the stroke origin.
//     Receivers apply their own `scale` (derived from their line-height).

const MAX_MESSAGE_BYTES = 64 * 1024;
const MAX_POINTS_PER_STROKE = 10_000;
const MAX_CONNECTIONS = 100;
const STROKE_BEGIN_RATE_LIMIT_MS = 2_000;
const MAX_STROKES_ON_WALL = 30;

// Server -> client
//   hello         { type, clientId }
//   wall-state    { type, strokes: [{strokeId, clientId, originXFrac, originYFrac,
//                                    points, complete}] } -- oldest first
//   stroke-begin  { type, strokeId, clientId, originXFrac, originYFrac }
//   stroke-points { type, strokeId, points }
//   stroke-end    { type, strokeId }
//   stroke-abort  { type, strokeId }   -- an in-flight stroke was abandoned
//                                         (drawer disconnected). Receivers drop
//                                         the partial; it does NOT become a
//                                         finished line. Distinct from
//                                         stroke-end, which commits the stroke.
//
// Client -> server
//   stroke-begin  { type, strokeId, originXFrac, originYFrac }
//   stroke-points { type, strokeId, points }   -- batched per animation frame
//   stroke-end    { type, strokeId }
//
// A `point` is { x, y, w, alpha, fadeOffset } -- fadeOffset is generated by
// the originator so every viewer sees the same chalk-wear pattern on the same
// stroke. Anything else on a point is ignored.

function isNum(v) {
  return typeof v === 'number' && Number.isFinite(v);
}

function isFrac(v) {
  return isNum(v) && v >= -0.5 && v <= 1.5; // tolerate slight overshoot
}

function sanitizePoint(p) {
  if (!p || typeof p !== 'object') return null;
  if (!isNum(p.x) || !isNum(p.y) || !isNum(p.w) || !isNum(p.alpha)) return null;
  const fadeOffset = isNum(p.fadeOffset) ? p.fadeOffset : Math.random();
  return { x: p.x, y: p.y, w: p.w, alpha: p.alpha, fadeOffset };
}

function parseClientMessage(raw) {
  if (typeof raw !== 'string') return { error: 'binary-unsupported' };
  if (raw.length > MAX_MESSAGE_BYTES) return { error: 'message-too-large' };
  let msg;
  try {
    msg = JSON.parse(raw);
  } catch {
    return { error: 'invalid-json' };
  }
  if (!msg || typeof msg !== 'object' || typeof msg.type !== 'string') {
    return { error: 'no-type' };
  }
  if (typeof msg.strokeId !== 'string' || msg.strokeId.length === 0 || msg.strokeId.length > 64) {
    return { error: 'bad-strokeId' };
  }
  if (msg.type === 'stroke-begin') {
    if (!isFrac(msg.originXFrac) || !isFrac(msg.originYFrac)) {
      return { error: 'bad-origin' };
    }
    return {
      msg: {
        type: 'stroke-begin',
        strokeId: msg.strokeId,
        originXFrac: msg.originXFrac,
        originYFrac: msg.originYFrac,
      },
    };
  }
  if (msg.type === 'stroke-points') {
    if (!Array.isArray(msg.points)) return { error: 'bad-points' };
    const points = [];
    for (const p of msg.points) {
      const sp = sanitizePoint(p);
      if (sp) points.push(sp);
    }
    return { msg: { type: 'stroke-points', strokeId: msg.strokeId, points } };
  }
  if (msg.type === 'stroke-end') {
    return { msg: { type: 'stroke-end', strokeId: msg.strokeId } };
  }
  return { error: 'unknown-type' };
}

module.exports = {
  MAX_MESSAGE_BYTES,
  MAX_POINTS_PER_STROKE,
  MAX_CONNECTIONS,
  STROKE_BEGIN_RATE_LIMIT_MS,
  MAX_STROKES_ON_WALL,
  parseClientMessage,
};
